### ISSUE TITLE
Unable to mount persistent volume the second time

### ISSUE THREAD

**Issue by fstn** [rosskukulinski/kubernetes-rethinkdb-cluster#39]
I try to use a persistent volume for my rethinkdb server. But I got this error:

```
Unable to mount volumes for pod "rethinkdb-server-deployment-6866f5b459-25fjb_default(efd90244-7d02-11e8-bffa-42010a8400b9)": timeout expired waiting for volumes to attach/mount for pod "default"/"rethinkdb-server-deployment-
Multi-Attach error for volume "pvc-f115c85e-7c42-11e8-bffa-42010a8400b9" Volume is already used by pod(s) rethinkdb-server-deployment-58f68c8464-4hn9x
```

I think that Kubernetes deploy a new node without removed the old one so it can't share le volume between both because my pvc is ReadWriteOnce. This persistent volume must be create in an automatic way, so I can't use persistent disk, format it ...

My configuration:
```

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: rethinkdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi



apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    db: rethinkdb
    role: admin
  name: rethinkdb-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rethinkdb-server
  template:
    metadata:
      name: rethinkdb-server-pod
      labels:
        app: rethinkdb-server
    spec:
      containers:
      - name: rethinkdb-server
        image: gcr.io/$PROJECT_ID/rethinkdb-server:$LAST_VERSION
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data/rethinkdb_data
          name: rethinkdb-storage
      volumes:
       - name: rethinkdb-storage
         persistentVolumeClaim:
          claimName: rethinkdb-pvc
```
How do you manage this?
Is it possible to share your Kubernetes config for that?

Thank you

**Comment by toredash** [comment]
You shouldn't use Deployment type with rethindb. Look into Statefulset.

If you still want to go the Deployment-type route, you need to specify the Recreate type: https://docs.openshift.com/container-platform/3.3/dev_guide/deployments/deployment_strategies.html#recreate-strategy

**Comment by fstn** [comment]
Thank you when I try the Statefulset, I got this:

`
E  error: Inaccessible database file: "/data/rethinkdb_data/metadata": No such file or directory
 E         Some possible reasons:
 E         - the database file couldn't be created or opened for reading and writing
 E         - the user which was used to start the database is not an owner of the file
`

It might be a right issue or a need to format the volume ... what do you think?

**Comment by toredash** [comment]
The error is quite clear IMHO of what's wrong. The UID on the database file is different than the user used to start rethindb.

Are you able to start a debug container on that PVC and check the UID/GID, and change it to what the image you are using to rub rethindb?

You could also just dump the database and reimport it with a new PV

**Comment by rosskukulinski** [comment]
Hi @toredash - thanks for jumping in to help!

@fstn - I agree with @toredash, you should look to leverage StatefulSets, not Deployments for the recommended way to run rethinkdb on k8s.

Could you please copy/paste the StatefulSet yaml you're using?

**Comment by fstn** [comment]
Thank you, this is my yml:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  labels:
    db: rethinkdb
    role: admin
  name: rethinkdb-server-deployment
spec:
  replicas: 1
  serviceName: "rethinkdb-driver"
  selector:
    matchLabels:
      app: rethinkdb-server
  template:
    metadata:
      name: rethinkdb-server-pod
      labels:
        app: rethinkdb-server
    spec:
      containers:
      - name: rethinkdb-server
        image: gcr.io/$PROJECT_ID/rethinkdb-server:$LAST_VERSION
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data/rethinkdb_data
          name: rethinkdb-storage
  volumeClaimTemplates:
      - metadata:
          name: rethinkdb-storage
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 20Gi
```

Works now bu I had to create the rethinkdb folder manualy before running the pod ;)
