### ISSUE TITLE
Issue with admin

### ISSUE THREAD

**Issue by esteban1983cl** [rosskukulinski/kubernetes-rethinkdb-cluster#42]
Hi, I have deployed the rethinkdb cluster in eks 1.13 following the statefulset folder instructions, but the admin deployment doesn't work:

Here is the log from admin deployment:

```txt
Using additional CLI flags:
Pod IP: 10.3.116.2
Pod namespace: default
Using service name: rethinkdb
Using server name: rethinkdb_admin_7c76b6b49_dvfgg
Checking for other nodes...
Using endpoints to lookup other nodes...
Endpoint url: https://10.100.0.1:443/api/v1/namespaces/default/endpoints/rethinkdb
Looking for IPs...
jq: error: Cannot iterate over null
No other nodes detected, will be a single instance.
Cannot start in proxy mode without endpoints.
```

thanks, please help

**Comment by esteban1983cl** [comment]
OK, I found the solution looking the docker image and run.sh script:
In admin deployment add the USE_SERVICE_LOOKUP variable:

```yaml
- name: POD_IP
  valueFrom:
     fieldRef:
       apiVersion: v1
       fieldPath: status.podIP
- name: RETHINK_CLUSTER
  value: rethinkdb
- name: USE_SERVICE_LOOKUP
  value: "true"
```

You need update the docs
Thanks for this app bro, very useful
